//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringIntegrationsScheduler.Job.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecurringIntegrationsScheduler.Job.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay upload of next file for {0} seconds.
        /// </summary>
        internal static string Delay_upload_of_next_file_for_0_seconds {
            get {
                return ResourceManager.GetString("Delay_upload_of_next_file_for_0_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} ended..
        /// </summary>
        internal static string Job_0_ended {
            get {
                return ResourceManager.GetString("Job_0_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Enqueuing failed for file: {1}. Failure response:  Status: {2}, Reason: {3}.
        /// </summary>
        internal static string Job_0_Enqueuing_failed_for_file_1_Failure_response_Status_2_Reason_3 {
            get {
                return ResourceManager.GetString("Job_0_Enqueuing_failed_for_file_1_Failure_response_Status_2_Reason_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failed to save status file. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failed_to_save_status_file_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Failed_to_save_status_file_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failed to save status log file. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failed_to_save_status_log_file_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Failed_to_save_status_log_file_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure processing file: {1} Exception : {2}.
        /// </summary>
        internal static string Job_0_Failure_processing_file_1_Exception_2 {
            get {
                return ResourceManager.GetString("Job_0_Failure_processing_file_1_Exception_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. File - {1} - found in input location..
        /// </summary>
        internal static string Job_0_File_1_found_in_input_location {
            get {
                return ResourceManager.GetString("Job_0_File_1_found_in_input_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. File: {1} - uploaded successfully. Message Id: {2}.
        /// </summary>
        internal static string Job_0_File_1_uploaded_successfully_Message_Id_2 {
            get {
                return ResourceManager.GetString("Job_0_File_1_uploaded_successfully_Message_Id_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Found {1} file(s) in input folder.
        /// </summary>
        internal static string Job_0_Found_1_file_s_in_input_folder {
            get {
                return ResourceManager.GetString("Job_0_Found_1_file_s_in_input_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Retrying HTTP operation. Exception : {1}.
        /// </summary>
        internal static string Job_0_Retrying_Http_operation_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Retrying_Http_operation_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Retrying IO operation. Exception : {1}.
        /// </summary>
        internal static string Job_0_Retrying_IO_operation_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Retrying_IO_operation_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} starting....
        /// </summary>
        internal static string Job_0_starting {
            get {
                return ResourceManager.GetString("Job_0_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Target directory for status log file was not specified.
        /// </summary>
        internal static string Job_0_Target_directory_for_status_log_file_was_not_specified {
            get {
                return ResourceManager.GetString("Job_0_Target_directory_for_status_log_file_was_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} thrown an error. Exception : {1}.
        /// </summary>
        internal static string Job_0_thrown_an_error_1 {
            get {
                return ResourceManager.GetString("Job_0_thrown_an_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Uploading file: {1}. File size: {2} bytes..
        /// </summary>
        internal static string Job_0_Uploading_file_1_File_size_2_bytes {
            get {
                return ResourceManager.GetString("Job_0_Uploading_file_1_File_size_2_bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} was paused because of an error..
        /// </summary>
        internal static string Job_0_was_paused_because_of_error {
            get {
                return ResourceManager.GetString("Job_0_was_paused_because_of_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} was paused indefinitely..
        /// </summary>
        internal static string Job_0_was_paused_indefinitely {
            get {
                return ResourceManager.GetString("Job_0_was_paused_indefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload job: {0} failed.
        /// </summary>
        internal static string Upload_job_0_failed {
            get {
                return ResourceManager.GetString("Upload_job_0_failed", resourceCulture);
            }
        }
    }
}
