//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringIntegrationsScheduler.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecurringIntegrationsScheduler.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD tenant id is missing in job configuration..
        /// </summary>
        internal static string AAD_tenant_id_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("AAD_tenant_id_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id of recurring job is missing or is not a GUID in job configuration..
        /// </summary>
        internal static string Activity_Id_of_recurring_job_is_missing_or_is_not_a_GUID_in_job_configuration {
            get {
                return ResourceManager.GetString("Activity_Id_of_recurring_job_is_missing_or_is_not_a_GUID_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOS URL is missing in job configuration..
        /// </summary>
        internal static string AOS_URL_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("AOS_URL_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure application client id is missing or is not a GUID in job configuration..
        /// </summary>
        internal static string Azure_application_client_id_is_missing_or_is_not_a_GUID_in_job_configuration {
            get {
                return ResourceManager.GetString("Azure_application_client_id_is_missing_or_is_not_a_GUID_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure authentication endpoint URL is missing in job configuration..
        /// </summary>
        internal static string Azure_authentication_endpoint_URL_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Azure_authentication_endpoint_URL_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure web application secret is missing in job configuration..
        /// </summary>
        internal static string Azure_web_application_secret_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Azure_web_application_secret_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse SortBy value in job configuration.
        /// </summary>
        internal static string Cannot_parse_SortBy_value_in_job_configuration {
            get {
                return ResourceManager.GetString("Cannot_parse_SortBy_value_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read a file {0}.
        /// </summary>
        internal static string Cannot_read_a_file_0 {
            get {
                return ResourceManager.GetString("Cannot_read_a_file_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is missing in job configuration..
        /// </summary>
        internal static string Company_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Company_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data project is missing in job configuration..
        /// </summary>
        internal static string Data_project_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Data_project_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download errors directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Download_errors_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Download_errors_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download errors directory is missing in job configuration..
        /// </summary>
        internal static string Download_errors_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Download_errors_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download success directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Download_success_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Download_success_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download success directory is missing in job configuration..
        /// </summary>
        internal static string Download_success_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Download_success_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name is missing in job configuration..
        /// </summary>
        internal static string Entity_name_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Entity_name_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving file: {0}. Error: {1}.
        /// </summary>
        internal static string Error_moving_file_0 {
            get {
                return ResourceManager.GetString("Error_moving_file_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file: {0}. Error: {1}.
        /// </summary>
        internal static string Error_saving_file_0 {
            get {
                return ResourceManager.GetString("Error_saving_file_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension of status files is missing in job configuration..
        /// </summary>
        internal static string Extension_of_status_files_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Extension_of_status_files_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} deleted successfully..
        /// </summary>
        internal static string File_0_deleted_successfully {
            get {
                return ResourceManager.GetString("File_0_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} saved successfully..
        /// </summary>
        internal static string File_0_saved_successfully {
            get {
                return ResourceManager.GetString("File_0_saved_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method GetAzureWriteUrl returned empty string. Check previous errors..
        /// </summary>
        internal static string GetAzureWriteUrl_returned_empty_string_Check_previous_errors {
            get {
                return ResourceManager.GetString("GetAzureWriteUrl_returned_empty_string_Check_previous_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Input_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Input_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input directory is missing in job configuration..
        /// </summary>
        internal static string Input_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Input_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing scheduler.
        /// </summary>
        internal static string Missing_scheduler {
            get {
                return ResourceManager.GetString("Missing_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active scheduler.
        /// </summary>
        internal static string No_active_scheduler {
            get {
                return ResourceManager.GetString("No_active_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package template: {0} was not found!.
        /// </summary>
        internal static string Package_template_0_not_found {
            get {
                return ResourceManager.GetString("Package_template_0_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Processing_errors_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Processing_errors_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors directory is missing in job configuration..
        /// </summary>
        internal static string Processing_errors_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Processing_errors_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing success directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Processing_success_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Processing_success_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing success directory is missing in job configuration..
        /// </summary>
        internal static string Processing_success_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Processing_success_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed at client..
        /// </summary>
        internal static string Request_failed_at_client {
            get {
                return ResourceManager.GetString("Request_failed_at_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Unknown_error {
            get {
                return ResourceManager.GetString("Unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload errors directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Upload_errors_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Upload_errors_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload errors directory is missing in job configuration..
        /// </summary>
        internal static string Upload_errors_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Upload_errors_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success directory does not exist or cannot be accessed..
        /// </summary>
        internal static string Upload_success_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Upload_success_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success directory is missing in job configuration..
        /// </summary>
        internal static string Upload_success_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Upload_success_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is missing in job configuration..
        /// </summary>
        internal static string User_password_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("User_password_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User principal name is missing in job configuration..
        /// </summary>
        internal static string User_principal_name_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("User_principal_name_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of package template file location failed! {0}.
        /// </summary>
        internal static string Verification_of_package_template_location_failed_0 {
            get {
                return ResourceManager.GetString("Verification_of_package_template_location_failed_0", resourceCulture);
            }
        }
    }
}
