//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringIntegrationsScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecurringIntegrationsScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string A_bout {
            get {
                return ResourceManager.GetString("A_bout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD application is not mapped to a user or mapped user has insufficient privileges assigned..
        /// </summary>
        internal static string AAD_application_is_not_mapped {
            get {
                return ResourceManager.GetString("AAD_application_is_not_mapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD authentication was successful.
        /// </summary>
        internal static string AAD_authentication_was_successful {
            get {
                return ResourceManager.GetString("AAD_authentication_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD application.
        /// </summary>
        internal static string AAD_client {
            get {
                return ResourceManager.GetString("AAD_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD client application is not selected..
        /// </summary>
        internal static string AAD_client_application_is_not_selected {
            get {
                return ResourceManager.GetString("AAD_client_application_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About_0 {
            get {
                return ResourceManager.GetString("About_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Recurring Integrations Scheduler.
        /// </summary>
        internal static string About_Recurring_Integrations_App {
            get {
                return ResourceManager.GetString("About_Recurring_Integrations_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to D365FO instance was successful..
        /// </summary>
        internal static string Access_to_D365FO_instance_was_successful {
            get {
                return ResourceManager.GetString("Access_to_D365FO_instance_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id.
        /// </summary>
        internal static string Activity_Id {
            get {
                return ResourceManager.GetString("Activity_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id (Guid) of this data job configured in Dynamics.
        /// </summary>
        internal static string Activity_Id_Guid_of_this_data_job_configured_in_Dynamics {
            get {
                return ResourceManager.GetString("Activity_Id_Guid_of_this_data_job_configured_in_Dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id is invalid.
        /// </summary>
        internal static string Activity_Id_is_invalid {
            get {
                return ResourceManager.GetString("Activity_Id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id is required.
        /// </summary>
        internal static string Activity_Id_is_required {
            get {
                return ResourceManager.GetString("Activity_Id_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_16xMD {
            get {
                object obj = ResourceManager.GetObject("Add_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Azure AD application.
        /// </summary>
        internal static string Add_Azure_AD_application {
            get {
                return ResourceManager.GetString("Add_Azure_AD_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Azure application.
        /// </summary>
        internal static string Add_Azure_application {
            get {
                return ResourceManager.GetString("Add_Azure_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data job.
        /// </summary>
        internal static string Add_data_job {
            get {
                return ResourceManager.GetString("Add_data_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add download job.
        /// </summary>
        internal static string Add_download_job {
            get {
                return ResourceManager.GetString("Add_download_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add export job (recommended).
        /// </summary>
        internal static string Add_export_job {
            get {
                return ResourceManager.GetString("Add_export_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add import job (recommended).
        /// </summary>
        internal static string Add_import_job {
            get {
                return ResourceManager.GetString("Add_import_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add instance.
        /// </summary>
        internal static string Add_instance {
            get {
                return ResourceManager.GetString("Add_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add job.
        /// </summary>
        internal static string Add_job {
            get {
                return ResourceManager.GetString("Add_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add job group.
        /// </summary>
        internal static string Add_job_group {
            get {
                return ResourceManager.GetString("Add_job_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add monitoring job.
        /// </summary>
        internal static string Add_monitoring_job {
            get {
                return ResourceManager.GetString("Add_monitoring_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to schedule.
        /// </summary>
        internal static string Add_to_schedule {
            get {
                return ResourceManager.GetString("Add_to_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add upload job.
        /// </summary>
        internal static string Add_upload_job {
            get {
                return ResourceManager.GetString("Add_upload_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string Add_user {
            get {
                return ResourceManager.GetString("Add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOS URL.
        /// </summary>
        internal static string AOS_URL {
            get {
                return ResourceManager.GetString("AOS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOS URL :.
        /// </summary>
        internal static string AOS_URL_ {
            get {
                return ResourceManager.GetString("AOS_URL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOS URL is invalid.
        /// </summary>
        internal static string AOS_URL_is_invalid {
            get {
                return ResourceManager.GetString("AOS_URL_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOS URL is required.
        /// </summary>
        internal static string AOS_URL_is_required {
            get {
                return ResourceManager.GetString("AOS_URL_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application client Id (GUID).
        /// </summary>
        internal static string Application_client_Id_GUID {
            get {
                return ResourceManager.GetString("Application_client_Id_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application type.
        /// </summary>
        internal static string Application_type {
            get {
                return ResourceManager.GetString("Application_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth endpoint.
        /// </summary>
        internal static string Auth_endpoint {
            get {
                return ResourceManager.GetString("Auth_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth type.
        /// </summary>
        internal static string Auth_type {
            get {
                return ResourceManager.GetString("Auth_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication endpoint :.
        /// </summary>
        internal static string Authentication_endpoint {
            get {
                return ResourceManager.GetString("Authentication_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication endpoint is required.
        /// </summary>
        internal static string Authentication_endpoint_is_required {
            get {
                return ResourceManager.GetString("Authentication_endpoint_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication endpoint URL is invalid.
        /// </summary>
        internal static string Authentication_endpoint_URL_is_invalid {
            get {
                return ResourceManager.GetString("Authentication_endpoint_URL_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication method.
        /// </summary>
        internal static string Authentication_method {
            get {
                return ResourceManager.GetString("Authentication_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication type.
        /// </summary>
        internal static string Authentication_type {
            get {
                return ResourceManager.GetString("Authentication_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD applications.
        /// </summary>
        internal static string Azure_AD_applications {
            get {
                return ResourceManager.GetString("Azure_AD_applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build cron expression at.
        /// </summary>
        internal static string Build_cron_expression_at {
            get {
                return ResourceManager.GetString("Build_cron_expression_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate next 100 runs of cron trigger.
        /// </summary>
        internal static string Calculate_next_100_runs_of_cron_trigger {
            get {
                return ResourceManager.GetString("Calculate_next_100_runs_of_cron_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if path does not contain illegal characters and if it exists and is accesible..
        /// </summary>
        internal static string Check_if_path {
            get {
                return ResourceManager.GetString("Check_if_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose AAD Client app.
        /// </summary>
        internal static string Choose_AAD_Client_app {
            get {
                return ResourceManager.GetString("Choose_AAD_Client_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user.
        /// </summary>
        internal static string Choose_user {
            get {
                return ResourceManager.GetString("Choose_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        internal static string Client_Id {
            get {
                return ResourceManager.GetString("Client_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id is invalid.
        /// </summary>
        internal static string Client_Id_is_invalid {
            get {
                return ResourceManager.GetString("Client_Id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id is required.
        /// </summary>
        internal static string Client_Id_is_required {
            get {
                return ResourceManager.GetString("Client_Id_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret.
        /// </summary>
        internal static string Client_secret {
            get {
                return ResourceManager.GetString("Client_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is required.
        /// </summary>
        internal static string Client_secret_is_required {
            get {
                return ResourceManager.GetString("Client_secret_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to scheduler service.
        /// </summary>
        internal static string Connect_to_scheduler_service {
            get {
                return ResourceManager.GetString("Connect_to_scheduler_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to service.
        /// </summary>
        internal static string Connect_to_service {
            get {
                return ResourceManager.GetString("Connect_to_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string Connected_to {
            get {
                return ResourceManager.GetString("Connected_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to standalone scheduler.
        /// </summary>
        internal static string Connected_to_standalone_scheduler {
            get {
                return ResourceManager.GetString("Connected_to_standalone_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string Connection_error {
            get {
                return ResourceManager.GetString("Connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron examples.
        /// </summary>
        internal static string Cron_examples {
            get {
                return ResourceManager.GetString("Cron_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron expression.
        /// </summary>
        internal static string Cron_expression {
            get {
                return ResourceManager.GetString("Cron_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron expression is invalid.
        /// </summary>
        internal static string Cron_expression_is_invalid {
            get {
                return ResourceManager.GetString("Cron_expression_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron trigger.
        /// </summary>
        internal static string Cron_trigger {
            get {
                return ResourceManager.GetString("Cron_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With cron expression you can specify schedules such as “every Friday at noon”, or “every weekday and 9:30 am”, or even “every 5 minutes between 9:00 am and 10:00 am on every Monday, Wednesday and Friday during January”.
        ///
        ///Default example above means: Each working day of the week (MON-FRI) run every 15 minutes (0/15) between 8:00 and 18:45 (8-18 - last run will be at 18:45).
        /// </summary>
        internal static string cronTriggerInfo {
            get {
                return ResourceManager.GetString("cronTriggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D365FO instance seems to be up and running..
        /// </summary>
        internal static string D365FO_instance_seems_to_be_up_and_running {
            get {
                return ResourceManager.GetString("D365FO_instance_seems_to_be_up_and_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D365FO instance seems to not support package API. Use only download and upload jobs..
        /// </summary>
        internal static string D365FO_instance_seems_to_not_support_package_API {
            get {
                return ResourceManager.GetString("D365FO_instance_seems_to_not_support_package_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D365FO instance seems to support package API. You can use export and import jobs..
        /// </summary>
        internal static string D365FO_instance_seems_to_support_package_API {
            get {
                return ResourceManager.GetString("D365FO_instance_seems_to_support_package_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data job.
        /// </summary>
        internal static string Data_job {
            get {
                return ResourceManager.GetString("Data_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data job is not selected..
        /// </summary>
        internal static string Data_job_is_not_selected {
            get {
                return ResourceManager.GetString("Data_job_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data job type.
        /// </summary>
        internal static string Data_job_type {
            get {
                return ResourceManager.GetString("Data_job_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data jobs.
        /// </summary>
        internal static string Data_jobs {
            get {
                return ResourceManager.GetString("Data_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data project.
        /// </summary>
        internal static string Data_project {
            get {
                return ResourceManager.GetString("Data_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data project is missing.
        /// </summary>
        internal static string Data_project_is_missing {
            get {
                return ResourceManager.GetString("Data_project_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default folder names.
        /// </summary>
        internal static string Default_folder_names {
            get {
                return ResourceManager.GetString("Default_folder_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Azure application.
        /// </summary>
        internal static string Delete_Azure_application {
            get {
                return ResourceManager.GetString("Delete_Azure_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job.
        /// </summary>
        internal static string Delete_job {
            get {
                return ResourceManager.GetString("Delete_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete package file.
        /// </summary>
        internal static string Delete_package_file {
            get {
                return ResourceManager.GetString("Delete_package_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download errors folder is not selected..
        /// </summary>
        internal static string Download_errors_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Download_errors_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder.
        /// </summary>
        internal static string Download_folder {
            get {
                return ResourceManager.GetString("Download_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder is not selected..
        /// </summary>
        internal static string Download_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Download_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download jobs folders names.
        /// </summary>
        internal static string Download_jobs_folders_names {
            get {
                return ResourceManager.GetString("Download_jobs_folders_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics 365 for Finance and Operations instances.
        /// </summary>
        internal static string Dynamics_365_for_Operations_instances {
            get {
                return ResourceManager.GetString("Dynamics_365_for_Operations_instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics details.
        /// </summary>
        internal static string Dynamics_details {
            get {
                return ResourceManager.GetString("Dynamics_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics instance is not selected..
        /// </summary>
        internal static string Dynamics_instance_is_not_selected {
            get {
                return ResourceManager.GetString("Dynamics_instance_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_16xMD {
            get {
                object obj = ResourceManager.GetObject("Edit_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Azure AD application.
        /// </summary>
        internal static string Edit_Azure_AD_application {
            get {
                return ResourceManager.GetString("Edit_Azure_AD_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Azure application.
        /// </summary>
        internal static string Edit_Azure_application {
            get {
                return ResourceManager.GetString("Edit_Azure_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data job.
        /// </summary>
        internal static string Edit_data_job {
            get {
                return ResourceManager.GetString("Edit_data_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit instance.
        /// </summary>
        internal static string Edit_instance {
            get {
                return ResourceManager.GetString("Edit_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job.
        /// </summary>
        internal static string Edit_job {
            get {
                return ResourceManager.GetString("Edit_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job {0}.
        /// </summary>
        internal static string Edit_job_0 {
            get {
                return ResourceManager.GetString("Edit_job_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job group.
        /// </summary>
        internal static string Edit_job_group {
            get {
                return ResourceManager.GetString("Edit_job_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string Edit_user {
            get {
                return ResourceManager.GetString("Edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name.
        /// </summary>
        internal static string Entity_name {
            get {
                return ResourceManager.GetString("Entity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name for this data job configured in Dynamics.
        /// </summary>
        internal static string Entity_name_for_this_data_job_configured_in_Dynamics {
            get {
                return ResourceManager.GetString("Entity_name_for_this_data_job_configured_in_Dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors folder.
        /// </summary>
        internal static string Errors_folder {
            get {
                return ResourceManager.GetString("Errors_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute import.
        /// </summary>
        internal static string Execute_import {
            get {
                return ResourceManager.GetString("Execute_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution monitor job for import job {0}.{1}.
        /// </summary>
        internal static string Execution_monitor_job_for_import_job_0_1 {
            get {
                return ResourceManager.GetString("Execution_monitor_job_for_import_job_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution monitoring job.
        /// </summary>
        internal static string Execution_monitoring_job {
            get {
                return ResourceManager.GetString("Execution_monitoring_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing application secret could not be decrypted! It was reset to empty value..
        /// </summary>
        internal static string Existing_application_secret_could_not_be_decrypted {
            get {
                return ResourceManager.GetString("Existing_application_secret_could_not_be_decrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing application secret could not be encrypted! It was reset to empty value..
        /// </summary>
        internal static string Existing_application_secret_could_not_be_encrypted {
            get {
                return ResourceManager.GetString("Existing_application_secret_could_not_be_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing password could not be decrypted! It was reset to empty value..
        /// </summary>
        internal static string Existing_password_could_not_be_decrypted {
            get {
                return ResourceManager.GetString("Existing_password_could_not_be_decrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing password could not be encrypted! It was reset to empty value..
        /// </summary>
        internal static string Existing_password_could_not_be_encrypted {
            get {
                return ResourceManager.GetString("Existing_password_could_not_be_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files filter and order.
        /// </summary>
        internal static string Files_filter_and_order {
            get {
                return ResourceManager.GetString("Files_filter_and_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter instances.
        /// </summary>
        internal static string Filter_instances {
            get {
                return ResourceManager.GetString("Filter_instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter job names.
        /// </summary>
        internal static string Filter_job_names {
            get {
                return ResourceManager.GetString("Filter_job_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_open_32xMD_exp {
            get {
                object obj = ResourceManager.GetObject("Folder_open_32xMD_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name.
        /// </summary>
        internal static string Friendly_name {
            get {
                return ResourceManager.GetString("Friendly_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name is required.
        /// </summary>
        internal static string Friendly_name_is_required {
            get {
                return ResourceManager.GetString("Friendly_name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name used only in Recurring Integrations App.
        /// </summary>
        internal static string Friendly_name_used_only_in_Recurring_Integrations_App {
            get {
                return ResourceManager.GetString("Friendly_name_used_only_in_Recurring_Integrations_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get cron schedule for monitor job .
        /// </summary>
        internal static string Get_cron_schedule_for_monitor_job {
            get {
                return ResourceManager.GetString("Get_cron_schedule_for_monitor_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get cron schedule for upload job .
        /// </summary>
        internal static string Get_cron_schedule_for_upload_job {
            get {
                return ResourceManager.GetString("Get_cron_schedule_for_upload_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method GetAzureWriteUrl returned empty string. Check previous errors..
        /// </summary>
        internal static string GetAzureWriteUrl_returned_empty_string_Check_previous_errors {
            get {
                return ResourceManager.GetString("GetAzureWriteUrl_returned_empty_string_Check_previous_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string Group_name {
            get {
                return ResourceManager.GetString("Group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname:.
        /// </summary>
        internal static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import details.
        /// </summary>
        internal static string Import_details {
            get {
                return ResourceManager.GetString("Import_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTED.
        /// </summary>
        internal static string IMPORTED {
            get {
                return ResourceManager.GetString("IMPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTED - CHANGE THIS!.
        /// </summary>
        internal static string IMPORTED_CHANGE_THIS {
            get {
                return ResourceManager.GetString("IMPORTED_CHANGE_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input folder.
        /// </summary>
        internal static string Input_folder {
            get {
                return ResourceManager.GetString("Input_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input folder is not selected..
        /// </summary>
        internal static string Input_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Input_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input subfolder.
        /// </summary>
        internal static string Input_subfolder {
            get {
                return ResourceManager.GetString("Input_subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance name :.
        /// </summary>
        internal static string Instance_name_ {
            get {
                return ResourceManager.GetString("Instance_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance seems to support GetMessageStatus method.
        /// </summary>
        internal static string Instance_seems_to_support_GetMessageStatus_method {
            get {
                return ResourceManager.GetString("Instance_seems_to_support_GetMessageStatus_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} in group {1} already exists in current schedule. Do you want to overwrite it?.
        /// </summary>
        internal static string Job_0_in_group_1_already_exists {
            get {
                return ResourceManager.GetString("Job_0_in_group_1_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job already exists!.
        /// </summary>
        internal static string Job_already_exists {
            get {
                return ResourceManager.GetString("Job_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job configuration is not valid.
        /// </summary>
        internal static string Job_configuration_is_not_valid {
            get {
                return ResourceManager.GetString("Job_configuration_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job details.
        /// </summary>
        internal static string Job_details {
            get {
                return ResourceManager.GetString("Job_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job group.
        /// </summary>
        internal static string Job_group {
            get {
                return ResourceManager.GetString("Job_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job group is not selected..
        /// </summary>
        internal static string Job_group_is_not_selected {
            get {
                return ResourceManager.GetString("Job_group_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job group name.
        /// </summary>
        internal static string Job_group_name {
            get {
                return ResourceManager.GetString("Job_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job group name is required.
        /// </summary>
        internal static string Job_group_name_is_required {
            get {
                return ResourceManager.GetString("Job_group_name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job groups.
        /// </summary>
        internal static string Job_groups {
            get {
                return ResourceManager.GetString("Job_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name.
        /// </summary>
        internal static string Job_name {
            get {
                return ResourceManager.GetString("Job_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name is missing..
        /// </summary>
        internal static string Job_name_is_missing {
            get {
                return ResourceManager.GetString("Job_name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job type.
        /// </summary>
        internal static string Job_type {
            get {
                return ResourceManager.GetString("Job_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs are still running. Are you sure You want to exit? Jobs will be terminated..
        /// </summary>
        internal static string Jobs_are_still_running_Are_you_sure_You_want_to_exit_Jobs_will_be_terminated {
            get {
                return ResourceManager.GetString("Jobs_are_still_running_Are_you_sure_You_want_to_exit_Jobs_will_be_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last run.
        /// </summary>
        internal static string Last_run {
            get {
                return ResourceManager.GetString("Last_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entity.
        /// </summary>
        internal static string Legal_entity {
            get {
                return ResourceManager.GetString("Legal_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entity is missing.
        /// </summary>
        internal static string Legal_entity_is_missing {
            get {
                return ResourceManager.GetString("Legal_entity_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entity (optional).
        /// </summary>
        internal static string Legal_entity_optional {
            get {
                return ResourceManager.GetString("Legal_entity_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login (UPN).
        /// </summary>
        internal static string Login_UPN {
            get {
                return ResourceManager.GetString("Login_UPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make exported file name unique.
        /// </summary>
        internal static string Make_exported_file_name_unique {
            get {
                return ResourceManager.GetString("Make_exported_file_name_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method GetMessageStatus returned empty string. KB4058074 is not installed..
        /// </summary>
        internal static string Method_GetMessageStatus_returned_empty_string_KB4058074_is_not_installed {
            get {
                return ResourceManager.GetString("Method_GetMessageStatus_returned_empty_string_KB4058074_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing scheduler.
        /// </summary>
        internal static string Missing_scheduler {
            get {
                return ResourceManager.GetString("Missing_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring jobs folders names.
        /// </summary>
        internal static string Monitoring_jobs_folders_names {
            get {
                return ResourceManager.GetString("Monitoring_jobs_folders_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More examples.
        /// </summary>
        internal static string More_examples {
            get {
                return ResourceManager.GetString("More_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next run.
        /// </summary>
        internal static string Next_run {
            get {
                return ResourceManager.GetString("Next_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active scheduler.
        /// </summary>
        internal static string No_active_scheduler {
            get {
                return ResourceManager.GetString("No_active_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string Not_connected {
            get {
                return ResourceManager.GetString("Not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open failed processing folder.
        /// </summary>
        internal static string Open_failed_processing_folder {
            get {
                return ResourceManager.GetString("Open_failed_processing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open failed uploads folder.
        /// </summary>
        internal static string Open_failed_uploads_folder {
            get {
                return ResourceManager.GetString("Open_failed_uploads_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open input folder.
        /// </summary>
        internal static string Open_input_folder {
            get {
                return ResourceManager.GetString("Open_input_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open successful downloads folder.
        /// </summary>
        internal static string Open_successful_downloads_folder {
            get {
                return ResourceManager.GetString("Open_successful_downloads_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open successful processing folder.
        /// </summary>
        internal static string Open_successful_processing_folder {
            get {
                return ResourceManager.GetString("Open_successful_processing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open successful uploads folder.
        /// </summary>
        internal static string Open_successful_uploads_folder {
            get {
                return ResourceManager.GetString("Open_successful_uploads_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        internal static string Order_by {
            get {
                return ResourceManager.GetString("Order_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite data project definition.
        /// </summary>
        internal static string Overwrite_data_project_definition {
            get {
                return ResourceManager.GetString("Overwrite_data_project_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package template.
        /// </summary>
        internal static string Package_template {
            get {
                return ResourceManager.GetString("Package_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist or is unaccessible.
        /// </summary>
        internal static string Path_doesnot_exist_or_is_unaccessible {
            get {
                return ResourceManager.GetString("Path_doesnot_exist_or_is_unaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all jobs.
        /// </summary>
        internal static string Pause_all_jobs {
            get {
                return ResourceManager.GetString("Pause_all_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause job.
        /// </summary>
        internal static string Pause_job {
            get {
                return ResourceManager.GetString("Pause_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Resume.
        /// </summary>
        internal static string Pause_Resume {
            get {
                return ResourceManager.GetString("Pause_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors folder.
        /// </summary>
        internal static string Processing_errors_folder {
            get {
                return ResourceManager.GetString("Processing_errors_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors folder is not selected..
        /// </summary>
        internal static string Processing_errors_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Processing_errors_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing monitor job.
        /// </summary>
        internal static string Processing_monitor_job {
            get {
                return ResourceManager.GetString("Processing_monitor_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing monitor job for upload job {0}.{1}.
        /// </summary>
        internal static string Processing_monitor_job_for_upload_job_0_1 {
            get {
                return ResourceManager.GetString("Processing_monitor_job_for_upload_job_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing monitoring job is not supported for direct editing. Please edit related upload job..
        /// </summary>
        internal static string Processing_monitoring_job_is_not_supported {
            get {
                return ResourceManager.GetString("Processing_monitoring_job_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing success folder.
        /// </summary>
        internal static string Processing_success_folder {
            get {
                return ResourceManager.GetString("Processing_success_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing success folder is not selected..
        /// </summary>
        internal static string Processing_success_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Processing_success_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartz cron triggers documentation.
        /// </summary>
        internal static string Quartz_cron_triggers_documentation {
            get {
                return ResourceManager.GetString("Quartz_cron_triggers_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        internal static string Recurrence {
            get {
                return ResourceManager.GetString("Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Integrations App.
        /// </summary>
        internal static string Recurring_Integrations_App {
            get {
                return ResourceManager.GetString("Recurring_Integrations_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Integrations Schedule|*.xml.
        /// </summary>
        internal static string Recurring_Integrations_Schedule_xml {
            get {
                return ResourceManager.GetString("Recurring_Integrations_Schedule_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Integrations Scheduler.
        /// </summary>
        internal static string Recurring_Integrations_Scheduler {
            get {
                return ResourceManager.GetString("Recurring_Integrations_Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh grid (F5).
        /// </summary>
        internal static string Refresh_grid {
            get {
                return ResourceManager.GetString("Refresh_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remove_16xMD {
            get {
                object obj = ResourceManager.GetObject("Remove_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume all jobs.
        /// </summary>
        internal static string Resume_all_jobs {
            get {
                return ResourceManager.GetString("Resume_all_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume job.
        /// </summary>
        internal static string Resume_job {
            get {
                return ResourceManager.GetString("Resume_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save schedule file.
        /// </summary>
        internal static string Save_schedule_file {
            get {
                return ResourceManager.GetString("Save_schedule_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search pattern.
        /// </summary>
        internal static string Search_pattern {
            get {
                return ResourceManager.GetString("Search_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        internal static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AAD client first!.
        /// </summary>
        internal static string Select_AAD_client_first {
            get {
                return ResourceManager.GetString("Select_AAD_client_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user first!.
        /// </summary>
        internal static string Select_user_first {
            get {
                return ResourceManager.GetString("Select_user_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service auth.
        /// </summary>
        internal static string Service_auth {
            get {
                return ResourceManager.GetString("Service_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service authentication.
        /// </summary>
        internal static string Service_authentication {
            get {
                return ResourceManager.GetString("Service_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple trigger.
        /// </summary>
        internal static string Simple_trigger {
            get {
                return ResourceManager.GetString("Simple_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start at.
        /// </summary>
        internal static string start_at {
            get {
                return ResourceManager.GetString("start_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start standalone scheduler.
        /// </summary>
        internal static string Start_standalone_scheduler {
            get {
                return ResourceManager.GetString("Start_standalone_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status check interval (sec.).
        /// </summary>
        internal static string Status_check_interval {
            get {
                return ResourceManager.GetString("Status_check_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status file extension.
        /// </summary>
        internal static string Status_file_extension {
            get {
                return ResourceManager.GetString("Status_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status file extension is not specified..
        /// </summary>
        internal static string Status_file_extension_is_not_specified {
            get {
                return ResourceManager.GetString("Status_file_extension_is_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id :.
        /// </summary>
        internal static string Tenant_Id {
            get {
                return ResourceManager.GetString("Tenant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id is required.
        /// </summary>
        internal static string Tenant_Id_is_required {
            get {
                return ResourceManager.GetString("Tenant_Id_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of job is not supported for direct editing..
        /// </summary>
        internal static string This_type_of_job_is_not_supported_for_direct_editing {
            get {
                return ResourceManager.GetString("This_type_of_job_is_not_supported_for_direct_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top upload folder.
        /// </summary>
        internal static string Top_upload_folder {
            get {
                return ResourceManager.GetString("Top_upload_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top uploads folder is not selected..
        /// </summary>
        internal static string Top_uploads_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Top_uploads_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger for job {0}.{1}.
        /// </summary>
        internal static string Trigger_for_job_0_1 {
            get {
                return ResourceManager.GetString("Trigger_for_job_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger status.
        /// </summary>
        internal static string Trigger_status {
            get {
                return ResourceManager.GetString("Trigger_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to scheduler {0} on {1}:{2}.
        /// </summary>
        internal static string Unable_to_connect_to_scheduler {
            get {
                return ResourceManager.GetString("Unable_to_connect_to_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create standalone scheduler.
        /// </summary>
        internal static string Unable_to_create_standalone_scheduler {
            get {
                return ResourceManager.GetString("Unable_to_create_standalone_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string Unexpected_error {
            get {
                return ResourceManager.GetString("Unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip package file.
        /// </summary>
        internal static string Unzip_package_file {
            get {
                return ResourceManager.GetString("Unzip_package_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload errors folder.
        /// </summary>
        internal static string Upload_errors_folder {
            get {
                return ResourceManager.GetString("Upload_errors_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload errors folder is not selected..
        /// </summary>
        internal static string Upload_errors_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Upload_errors_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload jobs folders names.
        /// </summary>
        internal static string Upload_jobs_folders_names {
            get {
                return ResourceManager.GetString("Upload_jobs_folders_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success folder.
        /// </summary>
        internal static string Upload_success_folder {
            get {
                return ResourceManager.GetString("Upload_success_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success folder is not selected..
        /// </summary>
        internal static string Upload_success_folder_is_not_selected {
            get {
                return ResourceManager.GetString("Upload_success_folder_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data packages.
        /// </summary>
        internal static string Uploading_data_packages {
            get {
                return ResourceManager.GetString("Uploading_data_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri or Guid.
        /// </summary>
        internal static string Uri_or_Guid {
            get {
                return ResourceManager.GetString("Uri_or_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default folder names.
        /// </summary>
        internal static string Use_default_folder_names {
            get {
                return ResourceManager.GetString("Use_default_folder_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default subfolders names.
        /// </summary>
        internal static string Use_default_subfolders_names {
            get {
                return ResourceManager.GetString("Use_default_subfolders_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User auth.
        /// </summary>
        internal static string User_auth {
            get {
                return ResourceManager.GetString("User_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authentication.
        /// </summary>
        internal static string User_authentication {
            get {
                return ResourceManager.GetString("User_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User credentials.
        /// </summary>
        internal static string User_credentials {
            get {
                return ResourceManager.GetString("User_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not enabled or has insufficient privileges assigned..
        /// </summary>
        internal static string User_is_not_enabled {
            get {
                return ResourceManager.GetString("User_is_not_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not selected..
        /// </summary>
        internal static string User_is_not_selected {
            get {
                return ResourceManager.GetString("User_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login is required.
        /// </summary>
        internal static string User_login_is_required {
            get {
                return ResourceManager.GetString("User_login_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login like: admin@contoso.com.
        /// </summary>
        internal static string User_login_like_admin_contoso_com {
            get {
                return ResourceManager.GetString("User_login_like_admin_contoso_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login (UPN).
        /// </summary>
        internal static string User_login_UPN {
            get {
                return ResourceManager.GetString("User_login_UPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is required.
        /// </summary>
        internal static string User_password_is_required {
            get {
                return ResourceManager.GetString("User_password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate instance settings.
        /// </summary>
        internal static string Validate_instance_settings {
            get {
                return ResourceManager.GetString("Validate_instance_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ValidateDocument_16x {
            get {
                object obj = ResourceManager.GetObject("ValidateDocument_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error(s).
        /// </summary>
        internal static string Validation_error {
            get {
                return ResourceManager.GetString("Validation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version_0 {
            get {
                return ResourceManager.GetString("Version_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! HTTP response status for D365FO instance is.
        /// </summary>
        internal static string Warning_HTTP_response_status_for_D365FO_instance_is {
            get {
                return ResourceManager.GetString("Warning_HTTP_response_status_for_D365FO_instance_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application client secret.
        /// </summary>
        internal static string Web_application_client_secret {
            get {
                return ResourceManager.GetString("Web_application_client_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed the schedule of running Recurring Integrations Scheduler service. You should save schedule file in scheduler service working folder to ensure that this schedule persist after service is shutdown.{0}Press OK to save the schedule or Cancel to continue without saving..
        /// </summary>
        internal static string You_have_changed_the_schedule {
            get {
                return ResourceManager.GetString("You_have_changed_the_schedule", resourceCulture);
            }
        }
    }
}
