//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringIntegrationsScheduler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadErrors")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string UploadErrorsFolder {
            get {
                return ((string)(this["UploadErrorsFolder"]));
            }
            set {
                this["UploadErrorsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadSuccess")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string UploadSuccessFolder {
            get {
                return ((string)(this["UploadSuccessFolder"]));
            }
            set {
                this["UploadSuccessFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProcessingSuccess")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string ProcessingSuccessFolder {
            get {
                return ((string)(this["ProcessingSuccessFolder"]));
            }
            set {
                this["ProcessingSuccessFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Errors")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DownloadErrorsFolder {
            get {
                return ((string)(this["DownloadErrorsFolder"]));
            }
            set {
                this["DownloadErrorsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Input")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string UploadInputFolder {
            get {
                return ((string)(this["UploadInputFolder"]));
            }
            set {
                this["UploadInputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProcessingErrors")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string ProcessingErrorsFolder {
            get {
                return ((string)(this["ProcessingErrorsFolder"]));
            }
            set {
                this["ProcessingErrorsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfDataJob xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <DataJob>
    <Name>Customers import</Name>
    <ActivityId>00000000-0000-0000-0000-000000000000</ActivityId>
    <EntityName>Customers</EntityName>
    <Type>Download</Type>
  </DataJob>
</ArrayOfDataJob>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::RecurringIntegrationsScheduler.Settings.DataJobs DataJobs {
            get {
                return ((global::RecurringIntegrationsScheduler.Settings.DataJobs)(this["DataJobs"]));
            }
            set {
                this["DataJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfInstance xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Instance>
    <Name>Contoso PROD</Name>
    <AosUri>https://contoso.production.operations.dynamics.com</AosUri>
    <AzureAuthEndpoint>https://login.microsoftonline.com</AzureAuthEndpoint>
    <AadTenant>contoso.com</AadTenant>
  </Instance>
</ArrayOfInstance>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::RecurringIntegrationsScheduler.Settings.Instances Instances {
            get {
                return ((global::RecurringIntegrationsScheduler.Settings.Instances)(this["Instances"]));
            }
            set {
                this["Instances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfUser xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <User>
    <Login>admin@contoso.com</Login>
    <Password>pass@word1</Password>
  </User>
</ArrayOfUser>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::RecurringIntegrationsScheduler.Settings.Users Users {
            get {
                return ((global::RecurringIntegrationsScheduler.Settings.Users)(this["Users"]));
            }
            set {
                this["Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfJobGroup xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <JobGroup>
    <Name>Import jobs</Name>
  </JobGroup>
  <JobGroup>
    <Name>Export jobs</Name>
  </JobGroup>
  <JobGroup>
    <Name>Download jobs</Name>
  </JobGroup>
  <JobGroup>
    <Name>Upload jobs</Name>
  </JobGroup>
</ArrayOfJobGroup>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::RecurringIntegrationsScheduler.Settings.JobGroups JobGroups {
            get {
                return ((global::RecurringIntegrationsScheduler.Settings.JobGroups)(this["JobGroups"]));
            }
            set {
                this["JobGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfAadApplication xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <AadApplication>
    <Name>User impersonation</Name>
    <ClientId>00000000-0000-0000-0000-000000000000</ClientId>
    <Secret />
    <AuthenticationType>User</AuthenticationType>
  </AadApplication>
  <AadApplication>
    <Name>Service to Service</Name>
    <ClientId>00000000-0000-0000-0000-000000000000</ClientId>
    <Secret />
    <AuthenticationType>Service</AuthenticationType>
  </AadApplication>
</ArrayOfAadApplication>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::RecurringIntegrationsScheduler.Settings.AadApplications AadApplications {
            get {
                return ((global::RecurringIntegrationsScheduler.Settings.AadApplications)(this["AadApplications"]));
            }
            set {
                this["AadApplications"] = value;
            }
        }
    }
}
