//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringIntegrationsScheduler.Job.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecurringIntegrationsScheduler.Job.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download job: {0} failed.
        /// </summary>
        internal static string Download_job_0_failed {
            get {
                return ResourceManager.GetString("Download_job_0_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Acknowledgment failure response:  Status: {1} - {2}, Reason: {3}.
        /// </summary>
        internal static string Job_0_Acknowledgment_failure_response {
            get {
                return ResourceManager.GetString("Job_0_Acknowledgment_failure_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Dequeued {1} file(s)..
        /// </summary>
        internal static string Job_0_Dequeued_1_file {
            get {
                return ResourceManager.GetString("Job_0_Dequeued_1_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Download failure. {1}.
        /// </summary>
        internal static string Job_0_Download_failure_1 {
            get {
                return ResourceManager.GetString("Job_0_Download_failure_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} ended..
        /// </summary>
        internal static string Job_0_ended {
            get {
                return ResourceManager.GetString("Job_0_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure during acknowledment of file. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_during_acknowledment_of_file {
            get {
                return ResourceManager.GetString("Job_0_Failure_during_acknowledment_of_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure during dequeueing files. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_during_dequeueing_files {
            get {
                return ResourceManager.GetString("Job_0_Failure_during_dequeueing_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure during download of files. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_during_download_of_files {
            get {
                return ResourceManager.GetString("Job_0_Failure_during_download_of_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure during unzipping a package file. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_during_unzipping_a_package_file {
            get {
                return ResourceManager.GetString("Job_0_Failure_during_unzipping_a_package_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure response:  Status: {1} - {2}, Reason: {3}.
        /// </summary>
        internal static string Job_0_Failure_response_Status_1_2_Reason_3 {
            get {
                return ResourceManager.GetString("Job_0_Failure_response_Status_1_2_Reason_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. File: {1} was acknowledged successfully..
        /// </summary>
        internal static string Job_0_File_1_was_acknowledged_successfully {
            get {
                return ResourceManager.GetString("Job_0_File_1_was_acknowledged_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. File: {1} was downloaded..
        /// </summary>
        internal static string Job_0_File_1_was_downloaded {
            get {
                return ResourceManager.GetString("Job_0_File_1_was_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. File dequeued successfully. Download location: {1}.
        /// </summary>
        internal static string Job_0_File_dequeued_successfully_Download_location_1 {
            get {
                return ResourceManager.GetString("Job_0_File_dequeued_successfully_Download_location_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Retrying HTTP operation. Exception : {1}.
        /// </summary>
        internal static string Job_0_Retrying_Http_operation_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Retrying_Http_operation_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Retrying IO operation. Exception : {1}.
        /// </summary>
        internal static string Job_0_Retrying_IO_operation_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Retrying_IO_operation_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} starting..
        /// </summary>
        internal static string Job_0_starting {
            get {
                return ResourceManager.GetString("Job_0_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} thrown an error. Exception : {1}.
        /// </summary>
        internal static string Job_0_thrown_an_error_1 {
            get {
                return ResourceManager.GetString("Job_0_thrown_an_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} was paused because of an error..
        /// </summary>
        internal static string Job_0_was_paused_because_of_error {
            get {
                return ResourceManager.GetString("Job_0_was_paused_because_of_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} was paused indefinitely..
        /// </summary>
        internal static string Job_0_was_paused_indefinitely {
            get {
                return ResourceManager.GetString("Job_0_was_paused_indefinitely", resourceCulture);
            }
        }
    }
}
