//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringIntegrationsScheduler.Job.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecurringIntegrationsScheduler.Job.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution monitor job: {0} failed.
        /// </summary>
        internal static string Execution_monitor_job_0_failed {
            get {
                return ResourceManager.GetString("Execution_monitor_job_0_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} ended..
        /// </summary>
        internal static string Job_0_ended {
            get {
                return ResourceManager.GetString("Job_0_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Execution status check request failed. Status code: {1}, Reason: {2}.
        /// </summary>
        internal static string Job_0_execution_status_check_request_failed_Status_code_1_Reason_2 {
            get {
                return ResourceManager.GetString("Job_0_execution_status_check_request_failed_Status_code_1_Reason_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure during moving files. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_during_moving_files_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Failure_during_moving_files_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure saving status file. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_saving_status_file_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Failure_saving_status_file_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure saving status log file. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_saving_status_log_file_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Failure_saving_status_log_file_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Failure while getting status of the job from Dynamics. Exception : {1}.
        /// </summary>
        internal static string Job_0_Failure_while_getting_status_of_the_job_from_Dynamics_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Failure_while_getting_status_of_the_job_from_Dynamics_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. File {1} - found in processing location and added to queue for status check..
        /// </summary>
        internal static string Job_0_File_1_found_in_processing_location_and_added_to_queue_for_status_check {
            get {
                return ResourceManager.GetString("Job_0_File_1_found_in_processing_location_and_added_to_queue_for_status_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Retrying HTTP operation. Exception : {1}.
        /// </summary>
        internal static string Job_0_Retrying_Http_operation_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Retrying_Http_operation_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Retrying IO operation. Exception : {1}.
        /// </summary>
        internal static string Job_0_Retrying_IO_operation_Exception_1 {
            get {
                return ResourceManager.GetString("Job_0_Retrying_IO_operation_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} starting....
        /// </summary>
        internal static string Job_0_starting {
            get {
                return ResourceManager.GetString("Job_0_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0}. Successfully received execution status for execution id: {1}.
        /// </summary>
        internal static string Job_0_Successfully_received_execution_status_for_execution_id_1 {
            get {
                return ResourceManager.GetString("Job_0_Successfully_received_execution_status_for_execution_id_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} thrown an error. Exception : {1}.
        /// </summary>
        internal static string Job_0_thrown_an_error_1 {
            get {
                return ResourceManager.GetString("Job_0_thrown_an_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} was paused because of an error..
        /// </summary>
        internal static string Job_0_was_paused_because_of_error {
            get {
                return ResourceManager.GetString("Job_0_was_paused_because_of_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: {0} was paused indefinitely..
        /// </summary>
        internal static string Job_0_was_paused_indefinitely {
            get {
                return ResourceManager.GetString("Job_0_was_paused_indefinitely", resourceCulture);
            }
        }
    }
}
